name = "EmmtRegistry"
uuid = "e94f2b12-43de-423d-83e5-babb893dc0f6"
repo = "https://github.com/emmt/EmmtRegistry"

[packages]
a977f4a2-36a7-4172-89e7-19c2726f82e5 = { name = "EasyFITS", path = "E/EasyFITS" }
