name = "EmmtRegistry"
uuid = "e94f2b12-43de-423d-83e5-babb893dc0f6"
repo = "https://github.com/emmt/EmmtRegistry"

[packages]
080ffe24-4a27-4ab0-ad71-7b624e73ef8d = { name = "OptimPackNextGen", path = "O/OptimPackNextGen" }
544ed34a-48a4-42df-8f69-6656fd9f4d48 = { name = "ConjugateGradient", path = "C/ConjugateGradient" }
7137afbe-ade3-4903-9296-05966c540d95 = { name = "ScientificDetectors", path = "S/ScientificDetectors" }
9d2c7f44-95c9-4219-b25f-7dc72cf9414a = { name = "AdaptiveOptics", path = "A/AdaptiveOptics" }
a6f1060a-fcb4-4ec9-a17b-f0f9a1d7da62 = { name = "AndorCameras", path = "A/AndorCameras" }
a977f4a2-36a7-4172-89e7-19c2726f82e5 = { name = "EasyFITS", path = "E/EasyFITS" }
b5817eee-6272-4252-97ed-5e273cea12dd = { name = "Tao", path = "T/Tao" }
c7119640-a72f-41a6-aa41-758559b204e7 = { name = "ScientificCameras", path = "S/ScientificCameras" }
e97054c3-40bb-4251-82f9-3abb7bf225d1 = { name = "TaoBindings", path = "T/TaoBindings" }
