name = "EmmtRegistry"
uuid = "e94f2b12-43de-423d-83e5-babb893dc0f6"
repo = "https://github.com/emmt/EmmtRegistry"

[packages]
080ffe24-4a27-4ab0-ad71-7b624e73ef8d = { name = "OptimPackNextGen", path = "O/OptimPackNextGen" }
7137afbe-ade3-4903-9296-05966c540d95 = { name = "ScientificDetectors", path = "S/ScientificDetectors" }
a977f4a2-36a7-4172-89e7-19c2726f82e5 = { name = "EasyFITS", path = "E/EasyFITS" }
b5817eee-6272-4252-97ed-5e273cea12dd = { name = "Tao", path = "T/Tao" }
