name = "EmmtRegistry"
uuid = "e94f2b12-43de-423d-83e5-babb893dc0f6"
repo = "https://github.com/emmt/EmmtRegistry"

[packages]
080ffe24-4a27-4ab0-ad71-7b624e73ef8d = { name = "OptimPackNextGen", path = "O/OptimPackNextGen" }
16730964-a2ec-11e9-36fa-47a4f82bfac6 = { name = "InterpolationKernels", path = "I/InterpolationKernels" }
1afde568-c220-478b-8c78-633644781b80 = { name = "LibUSB", path = "L/LibUSB" }
26e58924-7088-4c52-a09b-339225018a32 = { name = "PairedArrays", path = "P/PairedArrays" }
2fc109c4-9d77-11e9-32ff-e5c650334c16 = { name = "LinearInterpolators", path = "L/LinearInterpolators" }
30b38841-0f52-47f8-a5f8-18d5d4064379 = { name = "QuickHeaps", path = "Q/QuickHeaps" }
482535f4-4eff-4998-8428-5ff2b5e59f9e = { name = "AstronomicalDetectors", path = "A/AstronomicalDetectors" }
4995ad59-ea22-4881-abe2-ae7e9062fb98 = { name = "Alpao", path = "A/Alpao" }
534671aa-9d76-11e9-0200-554c6844f1ff = { name = "FineShift", path = "F/FineShift" }
544ed34a-48a4-42df-8f69-6656fd9f4d48 = { name = "ConjugateGradient", path = "C/ConjugateGradient" }
59a21e54-00bc-4653-8d10-290de9306ebc = { name = "PointSpreadFunctions", path = "P/PointSpreadFunctions" }
7137afbe-ade3-4903-9296-05966c540d95 = { name = "ScientificDetectors", path = "S/ScientificDetectors" }
83f21cc0-8014-4203-be99-7f9a344a7887 = { name = "IndexingTools", path = "I/IndexingTools" }
86c6b398-e7f6-4237-a185-b5d3f59d0094 = { name = "ArcusPerformax", path = "A/ArcusPerformax" }
9b8a2eb5-3725-4372-9eb1-1eb11fa2fbbe = { name = "ThemisAO", path = "T/ThemisAO" }
9d2c7f44-95c9-4219-b25f-7dc72cf9414a = { name = "AdaptiveOptics", path = "A/AdaptiveOptics" }
a6f1060a-fcb4-4ec9-a17b-f0f9a1d7da62 = { name = "AndorCameras", path = "A/AndorCameras" }
a977f4a2-36a7-4172-89e7-19c2726f82e5 = { name = "EasyFITS", path = "E/EasyFITS" }
b056ee54-6bb4-44e7-9abb-abfb59909e18 = { name = "BaseFITS", path = "B/BaseFITS" }
b5817eee-6272-4252-97ed-5e273cea12dd = { name = "Tao", path = "T/Tao" }
bd0ea217-0861-4661-bed1-3e8ea598dd25 = { name = "EasyRanges", path = "E/EasyRanges" }
bd3f2295-c078-4c6c-b43c-22dc7ee51ce3 = { name = "SolarWavefrontSensing", path = "S/SolarWavefrontSensing" }
bfa79951-833f-460b-a5a3-57213acc08ae = { name = "SimpleExpressions", path = "S/SimpleExpressions" }
c7119640-a72f-41a6-aa41-758559b204e7 = { name = "ScientificCameras", path = "S/ScientificCameras" }
c904d999-9673-4878-a3dd-e3ef1851788a = { name = "Unitless", path = "U/Unitless" }
d98d927a-eebc-4e2e-bfd8-b8854602986e = { name = "CenterOfGravity", path = "C/CenterOfGravity" }
e97054c3-40bb-4251-82f9-3abb7bf225d1 = { name = "TaoBindings", path = "T/TaoBindings" }
e9d32067-d496-40b5-8c90-e40f06d38009 = { name = "MultivariateOnlineStatistics", path = "M/MultivariateOnlineStatistics" }
f894539e-422c-4c16-819a-0e1d0163d378 = { name = "CartesianBoxes", path = "C/CartesianBoxes" }
ff9d1741-4d03-4fa8-9786-af30ea789bb0 = { name = "FITSBase", path = "F/FITSBase" }
